### ISSUE TITLE
Missing claims permission views

### ISSUE THREAD

**Issue by fasteddys** [PacktPublishing/ASP.NET-Core-Identity---Authentication-and-Authorization#1]
Hello this is not a strong enough sample to show case how to use claims to manage user groups dynamically like multitenant apps or outside 3rd party vendors that may login into to an ASP web site.

Also its not ASP Core 6

**Comment by Sonakshis** [comment]
Yes, the course was written using .NET 5. Also, the request for multi-tenant authorization and 3rd party auth is outside of the scope of this course. These are good ideas for additional content. Thank you so much for your suggestion.
